### ISSUE TITLE
[Bug]: Unable to disconnect device in Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by athkdev** [friedrith/node-wifi#191]
### Expected behavior

The Wi-Fi device should get disconnected on a Linux based distribution (Ubuntu 20.04.3 LTS)

### Current behavior

Device continues to stay connected even after running `wifi.disconnect((error) => {})`.

The following is the error log that I get:
```
Error: Command failed: nmcli device disconnect
Error: No interface specified.

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'nmcli device disconnect'
}

```

### Which are the affected features

- [ ] node API
- [ ] CLI

### Which is your operating system?

Linux

### Environment

Ubuntu 20.04.3 LTS

### Version of node-wifi

2.0.16

### Steps to Reproduce

1. Connect to a device using `wifi.connect({ssid: 'ssid', password: 'password'}, () => {})` which works perfectly.
2. Try to disconnect using `wifi.disconnect((error) => {})`.

### Solutions

Not sure at the moment, but happy to look into it.

**Comment by wrightd** [comment]
Dupe of #173 see workarounds in that issue.
